<a href="https://colab.research.google.com/github/Gopika-C/S3-Data-Science-Lab/blob/main/SIMPLE_KNN_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

In [ ]:
# Loading data
irisData = load_iris()

In [ ]:
# Create feature and target arrays
X = irisData.data
y = irisData.target

In [ ]:
# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

In [ ]:
knn = KNeighborsClassifier(n_neighbors=7)
    
knn.fit(X_train, y_train) # Fit the classifier to the training data

KNeighborsClassifier(n_neighbors=7)

In [ ]:
 y_pred=knn.predict(X_test)
    
 print(y_pred)

[1 0 2 1 1 0 1 2 2 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30



In [ ]:
print(accuracy_score(y_test,y_pred)*100)

96.66666666666667
